In [1]:
import numpy as np

In [43]:
# RLE 인코딩 함수
def rle_encode(mask):
    pixels = mask.flatten() # mask를 1차원으로 만든다.
    print(pixels)
    pixels = np.concatenate([[0], pixels, [0]]) # 양 끝에 0을 붙인다.
    print(pixels)
    print("1:", pixels[1:] )
    print(":-1", pixels[:-1] )
    print(pixels[1:] != pixels[:-1])
    runs = np.where(pixels[1:] != pixels[:-1])[0] + 1 # 1번부터(0번은 0이니까)
    print("runs", runs)
    print(runs[1::2])
    print(runs[::2])
    print(runs)
    runs[1::2] -= runs[::2]
    print(runs)
    return ' '.join(str(x) for x in runs)

# RLE 디코딩 함수
def rle_decode(mask_rle, shape):
    print(mask_rle)
    s = mask_rle.split()
    print(s)
    print(" ")
    print(s[0:])
    print([x for x in (s[0:][::2], s[1:][::2])])
    starts, lengths = [np.asarray(x, dtype=int) for x in (s[0:][::2], s[1:][::2])]
    print("d", starts, lengths)
    starts -= 1
    ends = starts + lengths
    img = np.zeros(shape[0]*shape[1], dtype=np.uint8)
    print(starts)
    print(ends)
    for lo, hi in zip(starts, ends):
        img[lo:hi] = 1
    return img.reshape(shape)

In [44]:
rle_decode("1 4 8 2 12 3", (2,7))

1 4 8 2 12 3
['1', '4', '8', '2', '12', '3']
 
['1', '4', '8', '2', '12', '3']
[['1', '8', '12'], ['4', '2', '3']]
d [ 1  8 12] [4 2 3]
[ 0  7 11]
[ 4  9 14]


array([[1, 1, 1, 1, 0, 0, 0],
       [1, 1, 0, 0, 1, 1, 1]], dtype=uint8)

In [23]:
mask = np.array([1,1,1,1,0,0,0,1,1,0,0,1,1,1])
a = rle_encode(mask)
print(a)

[1 1 1 1 0 0 0 1 1 0 0 1 1 1]
[0 1 1 1 1 0 0 0 1 1 0 0 1 1 1 0]
1: [1 1 1 1 0 0 0 1 1 0 0 1 1 1 0]
:-1 [0 1 1 1 1 0 0 0 1 1 0 0 1 1 1]
[ True False False False  True False False  True False  True False  True
 False False  True]
runs [ 1  5  8 10 12 15]
[ 5 10 15]
[ 1  8 12]
[ 1  5  8 10 12 15]
[ 1  4  8  2 12  3]
1 4 8 2 12 3
